# Generated by Django 4.1.7 on 2024-05-28 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0002_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='post.jpg', upload_to='users/', verbose_name='Image'),
        ),
    ]
