# Generated by Django 4.1.7 on 2024-07-02 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_wishlist_wishlist_model_alter_post_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='stars_date',
            new_name='stars_begin',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AddField(
            model_name='post',
            name='skills',
            field=models.CharField(default='', help_text='My skills', max_length=100, verbose_name='skills'),
        ),
        migrations.AlterField(
            model_name='postimages',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='images of post/'),
        ),
    ]
