# Generated by Django 4.1.7 on 2024-07-02 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_stars_date_post_stars_begin_remove_post_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postreview',
            name='review',
            field=models.CharField(default='', help_text='Review', max_length=200, verbose_name='review'),
        ),
    ]
