# Generated by Django 4.1.7 on 2024-07-04 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_postreview_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='email_address',
            new_name='email',
        ),
    ]
