# Generated by Django 4.1.7 on 2024-07-06 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimages',
            name='description',
        ),
        migrations.AddField(
            model_name='postimages',
            name='libellé',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='libellé'),
        ),
    ]
