<<<<<<< HEAD
# Generated by Django 4.1.7 on 2024-08-30 21:06

from django.db import migrations, models
import django.db.models.deletion
=======
# Generated by Django 5.1 on 2024-08-29 12:37

import django.db.models.deletion
from django.db import migrations, models
>>>>>>> a51575dbc2ac1af482ac05c6927e9a492f8d84d4


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_postimages_description_postimages_libellé'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wishlist_model',
            options={'ordering': ['-date'], 'verbose_name_plural': 'wishlists'},
        ),
        migrations.AlterField(
            model_name='postimages',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post', to='app.post', verbose_name='post'),
        ),
    ]
