# Generated by Django 5.1 on 2024-12-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_created',
            new_name='posted_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date_updated',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='', help_text='Title of post', max_length=100, unique=True, verbose_name='title'),
        ),
    ]
