# Generated by Django 5.1.3 on 2025-10-11 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='note',
            field=models.CharField(max_length=1000, null=True, verbose_name='note'),
        ),
    ]
