# Generated by Django 5.1.3 on 2025-10-23 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_post_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='app.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='ville',
            field=models.IntegerField(choices=[(1, 'Adrar'), (2, 'Chelef'), (3, 'Agout'), (4, 'Oum Bouaghi'), (5, 'Batna'), (6, 'Bejaia'), (7, 'Beskra'), (8, 'Bechar'), (9, 'Blida'), (10, 'Bouira'), (11, 'Tamanrasset'), (12, 'Tébessa'), (13, 'Tlemcen'), (14, 'Tiaret'), (15, 'Tizi Ouzou'), (16, 'Alger'), (17, 'Djelfa'), (18, 'Jijel'), (19, 'Setif'), (20, 'Saïda'), (21, 'Skikda'), (22, 'Sidi Bel Abbès'), (23, 'Annaba'), (24, 'Guelma'), (25, '25.Constantine'), (26, 'Médéa'), (27, 'Mostaganem'), (28, "M'Sila"), (29, 'Mascara'), (30, '30.Ouargla'), (31, 'Oran'), (32, 'El Bayadh'), (33, 'Illizi'), (34, 'Bordj Bou Arreridj'), (35, 'Boumerdès'), (36, 'El Tarf'), (37, 'Tindouf'), (38, 'Tissemsilt'), (39, 'El Oued'), (40, 'Khenchela'), (41, 'Souk Ahras'), (42, 'Tipaza'), (43, 'Mila'), (44, 'Aïn Defla'), (45, 'Naâma'), (46, 'Aïn Témouchent'), (47, 'Ghardaïa'), (48, 'Relizane'), (49, 'Timimoun'), (50, 'Bordj Badji Mokhtar'), (51, 'Ouled Djellal'), (52, 'Béni Abbèss'), (53, 'In Salah'), (54, 'In Guezzam'), (55, 'Touggourt '), (56, 'Djanet'), (57, 'El Maghaier'), (58, 'El Menia')], verbose_name='Ville'),
        ),
    ]
